import { EFFECT_LIMITS, effectInstanceSchema, type EffectInstance } from "../../shared/effects";

/**
 * Re-validates effect instances with the Zod schema.
 *
 * The Convex validators generated by `zodToConvex` only carry the *shape*;
 * refinements such as radius bounds are dropped. The client already clamps,
 * but a client is not a trust boundary, so mutations that persist instances
 * must run them through here first. Throws a readable message for the first
 * violation.
 */
export function assertEffectInstances(instances: readonly EffectInstance[], where: string): EffectInstance[] {
  if (instances.length > EFFECT_LIMITS.maxInstancesPerScene) {
    throw new Error(`${where} may hold at most ${EFFECT_LIMITS.maxInstancesPerScene} effects`);
  }

  const seen = new Set<string>();
  const parsed: EffectInstance[] = [];
  for (const instance of instances) {
    const result = effectInstanceSchema.safeParse(instance);
    if (!result.success) {
      const first = result.error.issues[0];
      const path = first?.path.join(".") ?? "";
      throw new Error(`Invalid effect instance in ${where}${path ? ` at ${path}` : ""}: ${first?.message ?? "unknown"}`);
    }
    if (seen.has(result.data.id)) {
      throw new Error(`Duplicate effect instance id "${result.data.id}" in ${where}`);
    }
    seen.add(result.data.id);
    parsed.push(result.data);
  }
  return parsed;
}
